//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandiriInhealth
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillLevel
    {
        public int skillLevelId { get; set; }
        public string skillLevelName { get; set; }
    }
}
